apiVersion: v1
kind: Pod
metadata:
  name: g4
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: prueba
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: prueba
    flexVolume:
      driver: "stackpointcloud/digitalocean-flex-volume"
      fsType: "ext4"
      options:
        volumeName: "prueba4"
        volumeID: "id0123456789"
